### ISSUE TITLE
firemaw

### ISSUE THREAD

**Issue by isitLoVe** [Flierr/BigWigs#11]
wing buffed should be 25 secs bar after each cast. combatlog is working.

**Comment by Flierr** [comment]
The repeat timer is set to 25 seconds.

I set the initial timer to 27 seconds based on an eduated guess (What i saw in firemaw).

For details see #12

**Comment by isitLoVe** [comment]
firemaw: http://pastebin.com/5tVNqRum
wing buffed timer
00:00:25 initial
00:00:49
00:00:51
00:00:50
flame buffed correct
shadow flame:
00:00:31 initial
00:00:17
00:00:16
00:00:16
00:00:18
00:00:16
00:00:18
