### ISSUE TITLE
ebonroc

### ISSUE THREAD

**Issue by isitLoVe** [Flierr/BigWigs#12]
I cannot find combatlog info on wing buffed so the timer does not work. the other dragons create a combatlog entry when casting wing buffed

**Comment by Flierr** [comment]
Combatlog:

7/4 22:50:06.131  Curx 's Insect Swarm was resisted by Ebonroc7
7/4 22:50:35.108  Ebonroc begins to cast Wing Buffet.
7/4 22:51:00.205  Ebonroc begins to cast Wing Buffet.
7/4 22:51:25.306  Ebonroc begins to cast Wing Buffet.

**Comment by Flierr** [comment]
The repeat timer is set to 25 seconds.

I set the initial timer to 27 seconds based on an eduated guess (What i saw in firemaw).

I implemented the same wing buffet timers on Firemaw and Flamegor (see issue #11 ) in the 19001 branch

**Comment by isitLoVe** [comment]
looks good to me - testing needed
