### ISSUE TITLE
Satura whirlwind

### ISSUE THREAD

**Issue by Flierr** [Flierr/BigWigs#14]
Timers are wrong. Will post combatlog soon.

**Comment by Flierr** [comment]
7/7 19:35:32.211  Underkraftet crits Battleguard Sartura for 308.

7/7 19:36:06.396  Battleguard Sartura 's Whirlwind missed Underkraftet.

7/7 19:36:48.597  Battleguard Sartura 's Whirlwind hits Kimbosliced for 2404.

**Comment by Flierr** [comment]
Fix attempt for whirlwind timer:

Initial whirlwind after 35 seconds, repeat timer 42 seconds. Implemented in the 19001 branch.

Testing next week.

**Comment by isitLoVe** [comment]
http://pastebin.com/TTuF63dn
whirlwind duration 15 sec
initial whirlwind after ~35 - 38 secs

**Comment by isitLoVe** [comment]
initial whirlwind 29 sec
whirlwind time in between
00:00:41
00:00:51
00:00:51
00:00:46
00:00:49
00:00:52
http://pastebin.com/gjWS73CW
