### ISSUE TITLE
Chromaggus initial breath

### ISSUE THREAD

**Issue by Flierr** [Flierr/BigWigs#17]
Chromaggus currently lacks a "first breath" timer.

So it would be a nice small update if we can implement a generic 30 seconds "First breath" timer that starts on the pull.

**Comment by isitLoVe** [comment]
here is your log mr flier
http://pastebin.com/AmCF2ES1

**Comment by isitLoVe** [comment]
need some values for vulnerability detection.
how much max dmg does an arcane spell when vuln is active / on a normal mob when fully buffed
how much max dmg does an nature spell when vuln is active / on a normal mob when fully buffed

**Comment by isitLoVe** [comment]
timer bar needs fix maybe do it with sync

**Comment by Flierr** [comment]
What do you mean by timer bar? You refer to weakness detection? Yeah you have to do that with sync.

Initial breath working correctly.

**Comment by isitLoVe** [comment]
the vuln
