### ISSUE TITLE
Stronk - Noth

### ISSUE THREAD

**Issue by isitLoVe** [Flierr/BigWigs#23]
Blink Timer, check if timer is fixed

**Comment by Flierr** [comment]
Need to do some good testing on this one. Since i think the blink timing is not consistent. -> perform multiple tests.

**Comment by isitLoVe** [comment]
i made about 5-10 tests with 1 balcony phase, the blink timer is accurate but sometimes, blink + curse happens at the same time
will test more when i have time

**Comment by isitLoVe** [comment]
working on test
