### ISSUE TITLE
BigWigs ThrottleSync

### ISSUE THREAD

**Issue by isitLoVe** [Flierr/BigWigs#24]
What does the 2nd parameter of the BigWigs_ThrottleSync do?

self:TriggerEvent("BigWigs_ThrottleSync", "HorsemenMeteor3", 8)

**Comment by Flierr** [comment]
I think its the fixed time where bigwigs will try to synch. Not sure yet relative to what the time is tho. Possibly repeating every x sec.

**Comment by isitLoVe** [comment]
found it: http://wow.gamepedia.com/BigWigs/API
