### ISSUE TITLE
Ouro all timers

### ISSUE THREAD

**Issue by Flierr** [Flierr/BigWigs#25]
I think that some of the timers on ouro were wrong. We should test all the timers.

I seem to remember my old bigwigs had a good timer for the "possible submerge" so we can use that, because i think its better than the current timer for that.

Mainly interested if the other ouro timers are correct.

**Comment by isitLoVe** [comment]
fun fact: 07/10/16 22:41:54.172 Ouro begins to cast Ragnaros Emerge. CHAT_MSG_SPELL_CREATURE_VS_CREATURE_BUFF",
