### ISSUE TITLE
4HM

### ISSUE THREAD

**Issue by isitLoVe** [Flierr/BigWigs#5]
the four horsemen (void zones later in the fight seem slightly longer than at the start)

**Comment by isitLoVe** [comment]
http://i.imgur.com/ZXAScvN.jpg
Data from Test Server

**Comment by isitLoVe** [comment]
current 12 sec repeater is not reliable
implement combatlog check for void zone and add bar 12 sec.
split meteor wrath and void zone bars

**Comment by isitLoVe** [comment]
get every1 to use this big wigs version so no wrong syncs are happening

**Comment by Flierr** [comment]
7/3 21:17:13.496  Lady Blaumeux hits Baifen for 436. (172 blocked) (1417 absorbed)
7/3 21:17:24.179  Baifen casts Void Zone.
7/3 21:17:36.130  You cast Void Zone.
7/3 21:17:48.213  Nirosx casts Void Zone.
7/3 21:18:00.314  Nirosx casts Void Zone.

7/3 21:20:25.317  Renew casts Void Zone.
7/3 21:20:37.417  You cast Void Zone.
7/3 21:20:49.567  Varua casts Void Zone.
7/3 21:21:01.584  You cast Void Zone.
7/3 21:21:13.537  Kayser casts Void Zone.

7/3 21:22:50.070  Renew casts Void Zone.
7/3 21:23:02.170  Kayser casts Void Zone.
7/3 21:23:14.270  Lindwynn casts Void Zone.
7/3 21:23:26.304  Kayser casts Void Zone.
7/3 21:23:38.354  Lindwynn casts Void Zone.

**Comment by Flierr** [comment]
Here is my proposed fix: http://paste2.org/5z2DeMbN

**Comment by isitLoVe** [comment]
tested new timer on testrealm looks good

**Comment by isitLoVe** [comment]
added 2 event types and made a new function for it to not spam the other functions
    self:RegisterEvent("CHAT_MSG_SPELL_HOSTILEPLAYER_DAMAGE", "VoidSkillEvent")
    self:RegisterEvent("CHAT_MSG_SPELL_FRIENDLYPLAYER_DAMAGE", "VoidSkillEvent")

here is the data from the live server https://paste.ee/p/zLvDa

**Comment by isitLoVe** [comment]
working on live
