### ISSUE TITLE
Baron Geddon Inferno

### ISSUE THREAD

**Issue by isitLoVe** [Flierr/BigWigs#6]
Baron Geddon Inferno Timer

**Comment by Flierr** [comment]
Tested the inferno timer. Combatlog:

7/2 15:50:51.471  Raigore 's Shoot Gun hits Baron Geddon for 73. (31 blocked)
7/2 15:51:35.687  Baron Geddon gains Inferno.

Changed the inferno timer from 40 s -> 45 s.

TODO: validate correctness of fix.

**Comment by Flierr** [comment]
All timers of Geddon are correct on live server.
